import { AssetInfo } from "@/types/telemetry";

export const INITIAL_ASSETS: AssetInfo[] = [
  {
    id: "turbine-1",
    name: "Alpha Turbine 01",
    type: "WIND_TURBINE",
    lat: 54.55,
    lng: 6.45,
    operatingMode: "ONLINE",
    locationName: "North Sea Array Alpha",
  },
  {
    id: "turbine-2",
    name: "Alpha Turbine 02",
    type: "WIND_TURBINE",
    lat: 54.58,
    lng: 6.48,
    operatingMode: "ONLINE",
    locationName: "North Sea Array Alpha",
  },
  {
    id: "turbine-3",
    name: "Alpha Turbine 03",
    type: "WIND_TURBINE",
    lat: 54.52,
    lng: 6.42,
    operatingMode: "MAINTENANCE_MODE",
    locationName: "North Sea Array Alpha",
  },
  {
    id: "turbine-4",
    name: "Beta Turbine 01",
    type: "WIND_TURBINE",
    lat: 54.60,
    lng: 6.55,
    operatingMode: "ONLINE",
    locationName: "North Sea Array Beta",
  },
  {
    id: "turbine-5",
    name: "Beta Turbine 02",
    type: "WIND_TURBINE",
    lat: 54.63,
    lng: 6.58,
    operatingMode: "ONLINE",
    locationName: "North Sea Array Beta",
  },
  {
    id: "microgrid-1",
    name: "Solar Microgrid East 01",
    type: "SOLAR_MICROGRID",
    lat: 54.48,
    lng: 6.38,
    operatingMode: "ONLINE",
    locationName: "Coastal Microgrid Station A",
  },
  {
    id: "microgrid-2",
    name: "Solar Microgrid East 02",
    type: "SOLAR_MICROGRID",
    lat: 54.45,
    lng: 6.35,
    operatingMode: "ONLINE",
    locationName: "Coastal Microgrid Station B",
  },
  {
    id: "turbine-6",
    name: "Gamma Turbine 01",
    type: "WIND_TURBINE",
    lat: 54.65,
    lng: 6.62,
    operatingMode: "ONLINE",
    locationName: "Deepwater Horizon Array",
  },
  {
    id: "turbine-7",
    name: "Gamma Turbine 02",
    type: "WIND_TURBINE",
    lat: 54.68,
    lng: 6.65,
    operatingMode: "ONLINE",
    locationName: "Deepwater Horizon Array",
  },
  {
    id: "substation-1",
    name: "Offshore Substation Main",
    type: "SUBSTATION",
    lat: 54.50,
    lng: 6.50,
    operatingMode: "ONLINE",
    locationName: "Central Hub Station",
  },
];
